logging:
  level.org.springframework: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3305/currency-database
    username: admin
    password: password
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

sql:
  init:
    mode: always